<script setup lang="ts">
const angles = ref<any[]>([]); const copies = ref<any[]>([]); const form = reactive({ angleId: '', type: 'affirmative_title', text: '' }); const bulk = ref(''); const categories = [['affirmative_title','Título afirmativo'],['question_title','Título pregunta'],['validation','Validación'],['benefit','Beneficio'],['promo','Promoción'],['cta','CTA'],['news','Noticia']]; const alert = useAlert()
async function load() { angles.value = await $fetch('/api/angles'); copies.value = await $fetch('/api/copies', { query: form.angleId ? { angleId: form.angleId } : {} }); if (!form.angleId) form.angleId = angles.value[0]?._id || '' }; onMounted(load)
watch(() => form.angleId, async id => { if (id) copies.value = await $fetch('/api/copies', { query: { angleId: id } }) })
async function add() { await $fetch('/api/copies', { method: 'POST', body: form }); form.text = ''; await load() }
async function addBulk() { const lines = bulk.value.split('\n').map(x => x.trim()).filter(Boolean); if (!lines.length) return; await Promise.all(lines.map(text => $fetch('/api/copies', { method: 'POST', body: { angleId: form.angleId, type: form.type, text } }))); bulk.value = ''; await load() }
async function remove(id: string) { if (await alert.confirm('Eliminar componente', '¿Quieres eliminar este texto?')) { await $fetch(`/api/copies/${id}`, { method: 'DELETE' }); await load(); await alert.success('Componente eliminado') } }
async function reset() { if (form.angleId && await alert.confirm('Restablecer componentes', 'Todos los textos del ángulo volverán a estar disponibles.')) { await $fetch(`/api/angles/${form.angleId}/reset`, { method: 'POST' }); await load(); await alert.success('Componentes restablecidos') } }
async function edit(item: any) { const text = await alert.prompt('Editar componente', item.text, 'Texto del componente'); if (text) { await $fetch(`/api/copies/${item._id}`, { method: 'PUT', body: { type: item.type, text } }); await load(); await alert.success('Componente actualizado') } }
</script>
<template><div class="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div class="mb-8"><NuxtLink to="/admin" class="text-sm font-semibold text-brand">← Administración</NuxtLink><h1 class="mt-3 text-4xl font-bold">Banco de copy</h1><p class="mt-3 text-slate-500">Edita cada frase o carga muchas líneas de una vez, una por línea.</p></div><div class="grid gap-6 lg:grid-cols-[340px_1fr]"><form class="card h-fit p-6" @submit.prevent="add"><p class="eyebrow">Añadir componente</p><div class="mt-5 space-y-3"><select v-model="form.angleId" class="input" required><option value="" disabled>Selecciona ángulo</option><option v-for="a in angles" :key="a._id" :value="a._id">{{ a.name }}</option></select><select v-model="form.type" class="input"><option v-for="c in categories" :key="c[0]" :value="c[0]">{{ c[1] }}</option></select><textarea v-model="form.text" class="input" rows="5" maxlength="500" placeholder="Una línea de copy..." required></textarea><button class="btn-primary w-full">Guardar componente</button><button type="button" class="btn-secondary w-full" @click="reset">Restablecer usados</button></div></form><section><div class="card mb-5 p-5"><p class="eyebrow">Carga masiva</p><p class="mt-1 text-sm text-slate-500">Usa el ángulo y tipo seleccionados. Cada línea crea un componente.</p><textarea v-model="bulk" class="input mt-3" rows="4" placeholder="Línea uno\nLínea dos\nLínea tres"></textarea><button class="btn-secondary mt-3" @click="addBulk">Cargar líneas</button></div><div class="mb-4 flex items-center justify-between"><h2 class="text-xl font-bold">{{ copies.length }} componentes</h2><span class="text-sm text-slate-500">{{ copies.filter(c => c.isUsed).length }} usados</span></div><div class="space-y-3"><div v-for="copy in copies" :key="copy._id" class="card flex items-start justify-between gap-4 p-4"><div><div class="mb-2 flex flex-wrap gap-2"><span class="rounded-full bg-brand/10 px-2 py-1 text-[10px] font-bold uppercase text-brand">{{ categories.find(c => c[0] === copy.type)?.[1] }}</span><span v-if="copy.isUsed" class="text-xs text-slate-400">Usado {{ copy.timesUsed }}×</span></div><p class="text-sm leading-relaxed">{{ copy.text }}</p></div><div class="flex shrink-0 gap-3"><button class="text-sm text-brand" @click="edit(copy)">Editar</button><button class="text-sm text-rose-500" @click="remove(copy._id)">×</button></div></div><div v-if="!copies.length" class="card p-10 text-center text-slate-500">Selecciona un ángulo o agrega el primer componente.</div></div></section></div></div></template>
