<script setup lang="ts">
type Angle = { _id: string; code?: string; name: string; nicheId?: { _id: string; name: string } | string }
type Parsed = { id: number; type: string; text: string; source: string }
const angles = ref<Angle[]>([]); const selectedAngle = ref(''); const fileName = ref(''); const parsed = ref<Parsed[]>([]); const dragging = ref(false); const importing = ref(false); const message = ref(''); const error = ref(''); const rawSource = ref(''); const bankDetected = ref(false); const bankPreview = ref<any[]>([])
const types: Record<string, string> = { affirmative_title: 'Título afirmativo', question_title: 'Título pregunta', validation: 'Validación', benefit: 'Beneficio', promo: 'Promoción', cta: 'CTA' }
const counts = computed(() => Object.fromEntries(Object.keys(types).map(type => [type, parsed.value.filter(x => x.type === type).length])))
function countAngle(angle: any) { return Object.values(angle.counts || {}).reduce((total: number, value: any) => total + Number(value || 0), 0) }
onMounted(async () => { angles.value = await $fetch<Angle[]>('/api/angles', { query: { active: true } }) })
function classify(text: string, tag: string, hint = '') {
  const value = `${hint} ${text}`.toLowerCase(); if (tag === 'h1' || tag === 'h2') return /\?/.test(text) ? 'question_title' : 'affirmative_title'; if (/\?/.test(text)) return 'question_title'; if (/pide|pídelo|quiero|deja tus datos|compra|prueba|actúa|descúbrelo|llama/.test(value)) return 'cta'; if (/descuento|envío|oferta|2×1|2x1|gratis|paga al recibir|solo hoy|promoci/.test(value)) return 'promo'; if (/paciente|testimonio|comprobad|miles|estrellas|resultados|entregad|confirma|natural|sin receta/.test(value)) return 'validation'; return tag === 'li' ? 'benefit' : 'affirmative_title'
}
async function parseContent(content: string, name: string) {
  rawSource.value = content; bankDetected.value = /ANG\.push\s*\(/.test(content)
  if (bankDetected.value) { parsed.value = []; fileName.value = name; try { const result = await $fetch<{ angles: any[] }>('/api/import/bank-preview', { method: 'POST', body: { source: content } }); bankPreview.value = result.angles; message.value = `Banco estructurado detectado: ${result.angles.length} ángulos listos para importar.`; error.value = '' } catch (e: any) { error.value = e?.data?.statusMessage || 'No se pudo leer la estructura ANG.' }; return }
  bankPreview.value = []
  const found: Parsed[] = []; const seen = new Set<string>(); const parser = new DOMParser(); const doc = parser.parseFromString(content, 'text/html'); const elements = Array.from(doc.querySelectorAll('h1,h2,h3,h4,li,p,[data-copy],[data-category],.title,.headline,.benefit,.validation,.promo,.cta'))
  for (const el of elements) { const text = (el.textContent || '').replace(/\s+/g, ' ').trim(); if (text.length < 4 || text.length > 500 || seen.has(text.toLowerCase())) continue; seen.add(text.toLowerCase()); const hint = `${el.className || ''} ${el.id || ''} ${el.getAttribute('data-category') || ''}`; found.push({ id: Date.now() + found.length, type: classify(text, el.tagName.toLowerCase(), hint), text, source: name }) }
  if (!found.length) content.split(/\r?\n/).map(x => x.trim()).filter(x => x.length >= 4).forEach((text, index) => found.push({ id: Date.now() + index, type: classify(text, 'p'), text: text.slice(0, 500), source: name }))
  parsed.value = found; fileName.value = name; message.value = `${found.length} frases detectadas.`; error.value = ''
}
function readFile(file: File) { if (!/\.(html?|txt)$/i.test(file.name)) { error.value = 'Solo se aceptan archivos .html, .htm o .txt'; return }; const reader = new FileReader(); reader.onload = () => { void parseContent(String(reader.result || ''), file.name) }; reader.readAsText(file) }
function inputFile(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (file) readFile(file) }
function drop(event: DragEvent) { dragging.value = false; const file = event.dataTransfer?.files?.[0]; if (file) readFile(file) }
function remove(id: number) { parsed.value = parsed.value.filter(item => item.id !== id) }
async function importAll() { if (bankDetected.value) { importing.value = true; try { const result = await $fetch<{ niches: number; angles: number; components: number }>('/api/import/bank', { method: 'POST', body: { source: rawSource.value } }); message.value = `Banco importado: ${result.niches} nichos, ${result.angles} ángulos y ${result.components} componentes nuevos.`; rawSource.value = ''; bankDetected.value = false; bankPreview.value = []; fileName.value = '' } catch (e: any) { error.value = e?.data?.statusMessage || 'No se pudo importar el banco.' } finally { importing.value = false }; return }; if (!selectedAngle.value || !parsed.value.length) { error.value = 'Selecciona un ángulo y asegúrate de tener frases detectadas.'; return }; importing.value = true; try { const result = await $fetch<{ imported: number; duplicates: number }>('/api/copies/bulk', { method: 'POST', body: { angleId: selectedAngle.value, items: parsed.value.map(({ type, text }) => ({ type, text })) } }); message.value = `Importadas ${result.imported} frases. Duplicadas omitidas: ${result.duplicates}.`; parsed.value = []; fileName.value = '' } catch (e: any) { error.value = e?.data?.statusMessage || 'No se pudo importar.' } finally { importing.value = false } }
</script>
<template>
  <div class="mx-auto max-w-7xl px-5 py-10 lg:px-8">
    <div class="mb-8"><NuxtLink to="/admin" class="text-sm font-semibold text-brand">← Administración</NuxtLink><h1 class="mt-3 text-4xl font-bold">Importador masivo</h1><p class="mt-3 max-w-2xl text-slate-500">Carga un HTML o TXT, revisa la clasificación y envía el banco al sistema.</p></div>
    <div v-if="error" class="mb-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{{ error }}</div><div v-if="message" class="mb-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{{ message }}</div>
    <div class="grid gap-6 lg:grid-cols-[360px_1fr]">
      <section class="space-y-5">
        <div class="card p-6"><p class="eyebrow">1 · Destino</p><h2 class="mt-2 text-xl font-bold">¿Dónde guardamos?</h2><div v-if="bankDetected" class="mt-4 rounded-xl bg-brand/10 p-4 text-sm text-brand">Banco `ANG.push` detectado. Se conservarán automáticamente nichos, códigos como N0/A1/P1 y categorías.</div><select v-else v-model="selectedAngle" class="input mt-4"><option value="" disabled>Elige un ángulo</option><option v-for="angle in angles" :key="angle._id" :value="angle._id">{{ angle.code || '?' }} · {{ angle.name }}</option></select></div>
        <div class="card p-6"><p class="eyebrow">2 · Archivo</p><label class="mt-4 flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-200 p-5 text-center hover:border-brand" :class="dragging ? 'border-brand bg-brand/5' : ''" @dragover.prevent="dragging = true" @dragleave.prevent="dragging = false" @drop.prevent="drop"><span class="text-3xl">⇧</span><strong class="mt-2">Arrastra el archivo aquí</strong><span class="mt-1 text-sm text-slate-500">o haz clic para buscar</span><span class="mt-3 text-xs text-slate-400">HTML, HTM o TXT</span><input type="file" accept=".html,.htm,.txt" class="hidden" @change="inputFile"></label><p v-if="fileName" class="mt-3 text-sm text-slate-500">Archivo: <b>{{ fileName }}</b></p></div>
      </section>
      <section class="card overflow-hidden">
        <div class="border-b border-slate-100 p-5"><p class="eyebrow">3 · Previsualización</p><div v-if="bankDetected" class="mt-4 space-y-3"><div class="flex items-center justify-between rounded-xl bg-amber-50 p-4 text-sm text-amber-800"><b>{{ bankPreview.length }} ángulos detectados</b><span>Se importarán todos</span></div><div class="max-h-[500px] overflow-y-auto rounded-xl border border-slate-100"><div v-for="angle in bankPreview" :key="angle.niche + angle.code" class="flex items-center justify-between gap-3 border-b border-slate-100 p-3 text-sm"><div><span class="mr-2 rounded bg-ink px-2 py-1 font-mono text-xs text-white">{{ angle.code }}</span><b>{{ angle.name }}</b><p class="mt-1 text-xs text-slate-400">{{ angle.niche }}</p></div><span class="text-xs text-slate-500">{{ countAngle(angle) }} frases</span></div></div></div><div v-else class="mt-3 grid grid-cols-3 gap-2 sm:grid-cols-6"><div v-for="(label, type) in types" :key="type" class="rounded-lg bg-slate-50 p-2 text-center"><p class="text-lg font-bold">{{ counts[type] || 0 }}</p><p class="text-[10px] text-slate-500">{{ label }}</p></div></div></div>
        <div v-if="!bankDetected" class="max-h-[500px] divide-y divide-slate-100 overflow-y-auto"><div v-for="item in parsed" :key="item.id" class="flex items-start gap-3 p-4"><select v-model="item.type" class="input !w-40 shrink-0 !px-2 !py-2 text-xs"><option v-for="(label, type) in types" :key="type" :value="type">{{ label }}</option></select><p class="flex-1 text-sm">{{ item.text }}</p><button class="text-sm text-rose-500" @click="remove(item.id)">×</button></div><div v-if="!parsed.length" class="p-16 text-center text-slate-400">Carga un archivo para comenzar.</div></div>
        <div class="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 p-5"><span class="text-sm text-slate-500">{{ bankDetected ? 'Banco completo listo' : parsed.length + ' frases listas' }}</span><button class="btn-primary" :disabled="importing || (!parsed.length && !bankDetected)" @click="importAll">{{ importing ? 'Importando...' : bankDetected ? 'Importar banco completo' : 'Importar a MongoDB' }}</button></div>
      </section>
    </div>
  </div>
</template>
