<script setup lang="ts">
type Item = { _id: string; type: string; text: string; isUsed: boolean; timesUsed: number }
const props = defineProps<{ angle: { _id: string; code?: string; name: string; description?: string; riskLevel?: string }; product: string; country: string }>()
const items = ref<Item[]>([]); const loading = ref(false); const output = ref<Record<string, any>>({}); const copied = ref(false); const toast = ref(''); const showBank = ref(false); const newType = ref('affirmative_title'); const newText = ref(''); const templateHtml = ref(''); const iframeRefs = ref<Record<string, HTMLIFrameElement>>({})
const labels: Record<string, string> = { affirmative_title: 'Título afirmativo', question_title: 'Título pregunta', validation: 'Validación', benefit: 'Beneficios', promo: 'Promoción', cta: 'CTA', news: 'Noticia' }
const riskLabels: Record<string, string> = { LOW: 'Bajo riesgo', MEDIUM: 'Riesgo medio', HIGH: 'Alto riesgo', EXTREME: 'Cuenta secundaria' }
const available = computed(() => items.value.filter(x => !x.isUsed)); const byType = (type: string) => available.value.filter(x => x.type === type)
function personalize(text: string) { return text.replaceAll('[Nombre]', props.product || '[Nombre]').replaceAll('[país]', props.country || '[país]') }
function pick(type: string) { const pool = byType(type); return pool.length ? pool[Math.floor(Math.random() * pool.length)] : null }
function pickUnique(type: string, used: Set<string>) { const pool = byType(type).filter(item => !used.has(item._id)); const item = pool.length ? pool[Math.floor(Math.random() * pool.length)] : null; if (item) used.add(item._id); return item }
function pickManyUnique(type: string, count: number, used: Set<string>) { return Array.from({ length: count }, () => pickUnique(type, used)).filter(Boolean) as Item[] }
function generate() { const validation = pick('validation'); const benefits = Array.from({ length: 4 }, () => pick('benefit')).filter(Boolean) as Item[]; output.value = { affirmative_title: pick('affirmative_title'), question_title: pick('question_title'), news: pick('news'), validation, benefit: benefits, promo: pick('promo'), cta: pick('cta') } }
function lote() { const used = new Set<string>(); const abo = [{ type: 'A', title: pickUnique('affirmative_title', used), validation: pickUnique('validation', used), benefits: pickManyUnique('benefit', 4, used), cta: pickUnique('cta', used) }, { type: 'B', title: pickUnique('question_title', used), validation: pickUnique('validation', used), benefits: pickManyUnique('benefit', 4, used), cta: pickUnique('cta', used) }, { type: 'C', title: pickUnique('news', used), promo: pickUnique('promo', used), validation: pickUnique('validation', used), benefits: pickManyUnique('benefit', 4, used), cta: pickUnique('cta', used) }] as any; output.value = { cta: abo[0].cta, abo } }
async function load() { loading.value = true; try { items.value = await $fetch<Item[]>('/api/copies', { query: { angleId: props.angle._id } }); generate() } finally { loading.value = false } }
watch(() => props.angle._id, load, { immediate: true })
onMounted(async () => { const templates = await $fetch<any[]>('/api/templates'); templateHtml.value = templates[0]?.html || '' })
function itemText(value: any) { return value?.text ? personalize(value.text) : 'Sin textos disponibles' }
const lines = computed(() => { const out: string[] = [`ÁNGULO: ${props.angle.name}`]; const abo: any[] = (output.value.abo as any[]) || []; if (abo.length) abo.forEach(image => { out.push(`\nIMAGEN ${image.type}: ${itemText(image.title)}`); if (image.promo) out.push(`PROMOCIÓN: ${itemText(image.promo)}`); out.push(`VALIDACIÓN: ${itemText(image.validation)}`, 'BENEFICIOS:', ...(image.benefits || []).map((x: Item) => `- ${personalize(x.text)}`), `CTA: ${itemText(image.cta || output.value.cta)}`) }); else Object.entries(output.value).forEach(([key, value]: any) => out.push(`${labels[key] || key}: ${Array.isArray(value) ? value.map(x => `- ${personalize(x.text)}`).join('\n') : itemText(value)}`)); return out })
async function copy() { await navigator.clipboard?.writeText(lines.value.join('\n')); copied.value = true; toast.value = 'Lote copiado al portapapeles'; setTimeout(() => { copied.value = false; toast.value = '' }, 1800) }
function displayedItems() { const abo: any[] = (output.value.abo as any[]) || []; return abo.length ? abo.flatMap(image => [image.title, image.promo, image.validation, image.cta, ...(image.benefits || [])]) : Object.values(output.value).flatMap(value => Array.isArray(value) ? value : [value]) }
function idsFromOutput() { const consumable = new Set(['affirmative_title', 'question_title']); return [...new Set(displayedItems().filter(item => item?._id && consumable.has(item.type)).map(item => item._id))] }
async function markUsed() { const ids = idsFromOutput(); if (ids.length) { await $fetch('/api/copies/mark-used', { method: 'POST', body: { ids } }); toast.value = `${ids.length} componentes marcados como usados`; setTimeout(() => toast.value = '', 1800); await load() } }
async function toggle(item: Item) { await $fetch(`/api/copies/${item._id}`, { method: 'PUT', body: { type: item.type, text: item.text, isUsed: !item.isUsed } }); await load() }
async function addLine() { if (!newText.value.trim()) return; await $fetch('/api/copies', { method: 'POST', body: { angleId: props.angle._id, type: newType.value, text: newText.value } }); newText.value = ''; await load() }
async function reset() { await $fetch(`/api/angles/${props.angle._id}/reset`, { method: 'POST' }); await load() }
function escapeHtml(text: string) { return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }
function assemble(image: any) { if (!templateHtml.value) return ''; const benefits = (image.benefits || []).map((item: Item) => `<li>✓ ${escapeHtml(personalize(item.text))}</li>`).join(''); const values: Record<string, string> = { TITULO_A: escapeHtml(personalize(image.type === 'B' ? itemText(image.title) : itemText(image.title))), TITULO_B: escapeHtml(itemText(output.value.question_title)), VALIDACION: escapeHtml(itemText(image.validation)), BENEFICIOS: benefits, PROMOCION: escapeHtml(itemText(image.promo)), CTA: escapeHtml(itemText(image.cta || output.value.cta)), PRODUCTO: escapeHtml(props.product || '[Nombre]'), PAIS: escapeHtml(props.country || '[país]') }; return templateHtml.value.replace(/\{\{([A-Z_]+)\}\}/g, (_match, key) => values[key] ?? '') }
const creatives = computed(() => { const abo: any[] = output.value.abo || []; return abo.map(image => ({ ...image, html: assemble(image) })) })
function setFrame(key: string, element: any) { if (element) iframeRefs.value[key] = element }
function downloadHtml(creative: any) { const blob = new Blob([creative.html], { type: 'text/html;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `creativo-${props.angle.code || props.angle.name}-${creative.type}.html`; link.click(); URL.revokeObjectURL(link.href) }
async function downloadPng(creative: any) { const frame = iframeRefs.value[creative.type]; const body = frame?.contentDocument?.documentElement; if (!body) return; const width = frame.clientWidth || 1080; const height = frame.clientHeight || 1080; const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml">${body.outerHTML}</div></foreignObject></svg>`; const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.getContext('2d')?.drawImage(image, 0, 0); const link = document.createElement('a'); link.download = `creativo-${creative.type}.png`; link.href = canvas.toDataURL('image/png'); link.click() }; image.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}` }
</script>
<template>
  <div class="space-y-5"><div class="card overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5 dark:border-slate-800"><div><div class="flex flex-wrap items-center gap-2"><p class="eyebrow">Ángulo activo</p><span class="rounded bg-ink px-2 py-1 font-mono text-xs font-bold text-white">{{ angle.code || '?' }}</span><span class="rounded-full px-2.5 py-1 text-xs font-bold" :class="{ LOW: 'bg-emerald-100 text-emerald-700', MEDIUM: 'bg-amber-100 text-amber-700', HIGH: 'bg-red-100 text-red-700', EXTREME: 'bg-red-200 text-red-800' }[angle.riskLevel || 'MEDIUM']">● {{ riskLabels[angle.riskLevel || 'MEDIUM'] }}</span></div><h3 class="mt-1 text-xl font-bold">{{ angle.name }}</h3><p class="mt-1 text-sm text-slate-500">{{ angle.description || 'Combinación lista para probar en campaña.' }}</p></div><div class="flex flex-wrap gap-2"><button class="btn-secondary" :disabled="loading" @click="generate">↻ Variación simple</button><button class="btn-primary" @click="lote">▦ Generar lote ABO</button><button class="btn-secondary" @click="copy">{{ copied ? 'Copiado ✓' : 'Copiar todo' }}</button><button class="btn-secondary" @click="markUsed">Marcar usados</button></div></div><div class="p-5"><div v-if="output.abo" class="grid gap-3 md:grid-cols-3"><div v-for="image in output.abo" :key="image.type" class="rounded-xl bg-slate-50 p-4 dark:bg-slate-800/70"><p class="mb-3 font-bold text-brand">Imagen {{ image.type }} <span v-if="image.promo" class="text-xs text-amber-600">+ promo</span></p><p class="font-semibold">{{ itemText(image.title) }}</p><p class="mt-3 text-xs text-slate-500">{{ itemText(image.validation) }}</p><ul class="mt-3 space-y-1 text-xs"><li v-for="benefit in image.benefits" :key="benefit?._id">✓ {{ personalize(benefit.text) }}</li></ul><p class="mt-3 text-xs font-bold">{{ itemText(output.cta) }}</p></div></div><div v-else class="grid gap-3 md:grid-cols-2"><div v-for="(value, key) in output" :key="key" class="rounded-xl bg-slate-50 p-4 dark:bg-slate-800/70"><p class="mb-2 text-[11px] font-bold uppercase tracking-wider text-slate-400">{{ labels[key] }}</p><ul v-if="Array.isArray(value)" class="space-y-1 text-sm"><li v-for="item in value" :key="item._id">{{ personalize(item.text) }}</li><li v-if="!value.length" class="text-rose-500">No quedan textos disponibles.</li></ul><p v-else class="text-sm">{{ itemText(value) }}</p></div></div></div><div class="flex flex-wrap gap-4 border-t border-slate-100 px-5 py-3 text-xs text-slate-500 dark:border-slate-800"><span>{{ available.length }} disponibles</span><span>{{ items.length - available.length }} usados</span><span>{{ items.length }} total</span><button class="ml-auto font-semibold text-brand" @click="showBank = !showBank">{{ showBank ? 'Ocultar banco' : 'Ver banco por categoría' }}</button></div></div>
  <div v-if="showBank" class="card p-5"><div class="mb-4 flex items-center justify-between"><div><p class="eyebrow">Banco del ángulo</p><h3 class="text-lg font-bold">Textos y trazabilidad</h3></div><button class="btn-secondary" @click="reset">Reiniciar usados</button></div><div class="grid gap-5 md:grid-cols-2"><div v-for="(label, type) in labels" :key="type"><div class="mb-2 flex justify-between text-xs font-bold"><span>{{ label }}</span><span :class="byType(type).length ? 'text-slate-400' : 'text-red-600'">{{ byType(type).length }} sin usar</span></div><div class="space-y-2"><label v-for="item in items.filter(x => x.type === type)" :key="item._id" class="flex gap-2 rounded-lg bg-slate-50 p-2 text-sm dark:bg-slate-800"><input type="checkbox" :checked="item.isUsed" class="mt-1 accent-brand" @change="toggle(item)"><span :class="item.isUsed ? 'text-slate-400 line-through' : ''">{{ item.text }}</span></label></div></div></div><form class="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-4" @submit.prevent="addLine"><select v-model="newType" class="input !w-auto"><option v-for="(label, type) in labels" :key="type" :value="type">{{ label }}</option></select><input v-model="newText" class="input min-w-[220px] flex-1" placeholder="Nueva línea de copy" maxlength="500"><button class="btn-primary">Agregar línea</button></form></div></div>
  <section v-if="templateHtml && creatives.length" class="card overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><p class="eyebrow">Preview visual</p><h3 class="mt-1 text-xl font-bold">Creativos ensamblados con plantilla</h3><p class="mt-1 text-sm text-slate-500">Los marcadores fueron reemplazados con el lote ABO activo.</p></div></div><div class="grid gap-5 p-5 lg:grid-cols-3"><article v-for="creative in creatives" :key="creative.type" class="overflow-hidden rounded-2xl border border-slate-200 bg-slate-50"><div class="flex items-center justify-between border-b border-slate-200 px-3 py-2"><b class="text-sm">Imagen {{ creative.type }}</b><div class="flex gap-1"><button class="btn-secondary !rounded-lg !px-2 !py-1 text-xs" @click="downloadHtml(creative)">HTML</button><button class="btn-secondary !rounded-lg !px-2 !py-1 text-xs" @click="downloadPng(creative)">PNG</button></div></div><iframe :ref="element => setFrame(creative.type, element)" :srcdoc="creative.html" class="h-[420px] w-full bg-white" sandbox=""></iframe></article></div></section><div v-else-if="!templateHtml" class="rounded-xl border border-dashed border-slate-300 p-5 text-sm text-slate-500">Configura una plantilla visual desde <NuxtLink to="/admin/templates" class="font-bold text-brand">Administración → Plantillas visuales</NuxtLink> para ver los anuncios renderizados.</div>
</template>
