<script setup lang="ts">
type Niche = { _id: string; name: string; description: string }; type Angle = { _id: string; code?: string; nicheId: string | { _id: string }; name: string; description: string; riskLevel?: string }
const niches = ref<Niche[]>([]); const angles = ref<Angle[]>([]); const selectedNiche = ref(''); const selectedAngle = ref(''); const error = ref(''); const product = useState('product'); const country = useState('country')
const risk: Record<string, string> = { LOW: 'bg-emerald-100 text-emerald-700', MEDIUM: 'bg-amber-100 text-amber-700', HIGH: 'bg-orange-100 text-orange-700', EXTREME: 'bg-red-100 text-red-700' }
const riskLabel: Record<string, string> = { LOW: 'Bajo', MEDIUM: 'Medio', HIGH: 'Alto', EXTREME: 'Extremo' }
async function loadNiches() { try { niches.value = await $fetch<Niche[]>('/api/niches', { query: { active: true } }); selectedNiche.value ||= niches.value[0]?._id || ''; await loadAngles() } catch (e: any) { error.value = e?.data?.statusMessage || 'No se pudo cargar el banco.' } }
async function loadAngles() { if (!selectedNiche.value) return; angles.value = await $fetch<Angle[]>('/api/angles', { query: { nicheId: selectedNiche.value, active: true } }); if (!angles.value.some(x => x._id === selectedAngle.value)) selectedAngle.value = angles.value[0]?._id || '' }
watch(selectedNiche, loadAngles); onMounted(loadNiches)
const currentAngle = computed(() => angles.value.find(x => x._id === selectedAngle.value))
</script>
<template>
    <div class="min-h-[calc(100vh-65px)] bg-[#f7f8fc] dark:bg-slate-950"><div class="flex min-h-[calc(100vh-65px)]"><aside class="hidden w-[286px] shrink-0 border-r border-slate-200 bg-white px-4 py-5 dark:border-slate-800 dark:bg-slate-900 md:block"><div class="mb-5 flex items-center justify-between px-2"><div><p class="eyebrow">Workspace</p><h2 class="mt-1 font-display text-lg font-bold">Biblioteca creativa</h2></div><span class="rounded-lg bg-brand/10 px-2 py-1 text-[10px] font-bold text-brand">ACTIVO</span></div><div class="mb-5 grid grid-cols-3 gap-1 rounded-xl bg-slate-100 p-1 dark:bg-slate-800"><button v-for="niche in niches" :key="niche._id" class="rounded-lg px-2 py-2 text-xs font-bold transition-all duration-200" :class="selectedNiche === niche._id ? 'bg-white text-brand shadow-sm dark:bg-slate-700' : 'text-slate-500'" @click="selectedNiche = niche._id">{{ niche.name.slice(0, 5) }}</button></div><p class="mb-2 px-2 text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Ángulos de venta</p><div class="space-y-1"><button v-for="angle in angles" :key="angle._id" class="group w-full rounded-xl border-l-2 px-3 py-3 text-left transition-all duration-200" :class="selectedAngle === angle._id ? 'border-brand bg-brand/5 shadow-sm' : 'border-transparent hover:bg-slate-50 dark:hover:bg-slate-800'" @click="selectedAngle = angle._id"><span class="flex items-center justify-between gap-2"><span class="flex min-w-0 items-center gap-2"><b class="rounded bg-ink px-1.5 py-0.5 font-mono text-[10px] text-white">{{ angle.code || '?' }}</b><span class="truncate text-sm font-semibold" :class="selectedAngle === angle._id ? 'text-brand' : 'text-slate-600 dark:text-slate-300'">{{ angle.name }}</span></span><span class="h-2 w-2 shrink-0 rounded-full" :class="{ LOW: 'bg-emerald-500', MEDIUM: 'bg-amber-500', HIGH: 'bg-orange-500', EXTREME: 'bg-red-500' }[angle.riskLevel || 'MEDIUM']"></span></span><span class="mt-2 block pl-8 text-[10px] font-bold uppercase tracking-wider" :class="risk[angle.riskLevel || 'MEDIUM']">{{ riskLabel[angle.riskLevel || 'MEDIUM'] }}</span></button><p v-if="!angles.length" class="px-2 py-5 text-sm text-slate-400">Sin ángulos activos.</p></div><div class="mt-8 border-t border-slate-100 pt-4 dark:border-slate-800"><NuxtLink to="/admin" class="flex items-center gap-2 rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-500 transition hover:bg-slate-50 hover:text-brand dark:hover:bg-slate-800">⚙ Administración</NuxtLink></div></aside>
<aside class="app-sidebar hidden w-[286px] shrink-0 border-r border-slate-200 bg-white px-4 py-5 dark:border-slate-800 dark:bg-slate-900 md:block"><div class="mb-5 flex items-center justify-between px-2"><div><p class="eyebrow">Workspace</p><h2 class="mt-1 font-display text-lg font-bold">Biblioteca creativa</h2></div><span class="rounded-lg bg-brand/10 px-2 py-1 text-[10px] font-bold text-brand">ACTIVO</span></div><div class="mb-5 grid grid-cols-3 gap-1 rounded-xl bg-slate-100 p-1 dark:bg-slate-800"><button v-for="niche in niches" :key="niche._id" class="rounded-lg px-2 py-2 text-xs font-bold transition-all duration-200" :class="selectedNiche === niche._id ? 'bg-white text-brand shadow-sm dark:bg-slate-700' : 'text-slate-500'" @click="selectedNiche = niche._id">{{ niche.name.slice(0, 5) }}</button></div><p class="mb-2 px-2 text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Ángulos de venta</p><div class="space-y-1"><button v-for="angle in angles" :key="angle._id" class="group w-full rounded-xl border-l-2 px-3 py-3 text-left transition-all duration-200" :class="selectedAngle === angle._id ? 'border-brand bg-brand/5 shadow-sm' : 'border-transparent hover:bg-slate-50 dark:hover:bg-slate-800'" @click="selectedAngle = angle._id"><span class="flex items-center justify-between gap-2"><span class="flex min-w-0 items-center gap-2"><b class="rounded bg-ink px-1.5 py-0.5 font-mono text-[10px] text-white">{{ angle.code || '?' }}</b><span class="truncate text-sm font-semibold" :class="selectedAngle === angle._id ? 'text-brand' : 'text-slate-600 dark:text-slate-300'">{{ angle.name }}</span></span><span class="h-2 w-2 shrink-0 rounded-full" :class="{ LOW: 'bg-emerald-500', MEDIUM: 'bg-amber-500', HIGH: 'bg-orange-500', EXTREME: 'bg-red-500' }[angle.riskLevel || 'MEDIUM']"></span></span><span class="mt-2 block pl-8 text-[10px] font-bold uppercase tracking-wider" :class="risk[angle.riskLevel || 'MEDIUM']">{{ riskLabel[angle.riskLevel || 'MEDIUM'] }}</span></button><p v-if="!angles.length" class="px-2 py-5 text-sm text-slate-400">Sin ángulos activos.</p></div><div class="mt-8 border-t border-slate-100 pt-4 dark:border-slate-800"><NuxtLink to="/admin" class="flex items-center gap-2 rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-500 transition hover:bg-slate-50 hover:text-brand dark:hover:bg-slate-800">⚙ Administración</NuxtLink></div></aside>
    <main class="min-w-0 flex-1 px-5 py-7 lg:px-9"><div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow">Media buying / Laboratorio creativo</p><h1 class="mt-2 font-display text-3xl font-bold tracking-tight md:text-4xl">Generador de creativos</h1><p class="mt-2 text-sm text-slate-500">Construye, prueba y registra cada variación de tu próximo anuncio.</p></div><div class="flex items-center gap-2 md:hidden"><select v-model="selectedNiche" class="input !w-auto bg-white text-slate-900 dark:bg-slate-800 dark:text-white"><option v-for="n in niches" :key="n._id" :value="n._id">{{ n.name }}</option></select><select v-model="selectedAngle" class="input !w-auto bg-white text-slate-900 dark:bg-slate-800 dark:text-white"><option v-for="a in angles" :key="a._id" :value="a._id">{{ a.code }} · {{ a.name }}</option></select></div></div><div v-if="error" class="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{{ error }}</div><div v-if="currentAngle" class="mb-5 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span>Producto: <b class="text-slate-900 dark:text-white">{{ product }}</b></span><span>•</span><span>Mercado: <b class="text-slate-900 dark:text-white">{{ country }}</b></span><span class="rounded-full bg-emerald-100 px-2 py-1 font-bold text-emerald-700">{{ currentAngle.code }}</span></div><CopyGenerator v-if="currentAngle" :angle="currentAngle" :product="product" :country="country" /><div v-else class="card p-14 text-center text-slate-500">Crea o activa un nicho y un ángulo desde Administración.</div></main></div></div>
</template>
